Unit tests
NREL-SIIP/WaterModelsAnalytics.jl pull request #43
Opened 2021-03-04 07:04 UTC by enzoliuyang94

Added unit tests for simulation.jl and validation.jl

2021-04-21 22:55 UTC, jjstickel requested changes
Please also add "include" lines for the new test files you created in `test/runtests.jl`.

2021-04-21 22:55 UTC, jjstickel commented on test/simulation.jl
> +
Any modules that are needed should be imported (not used) in `runtests.jl` not in the sub-test files.  Shortcuts for WaterModels and InfrastructureModels are already defined there.

2021-04-21 22:55 UTC, jjstickel commented on test/validation.jl
> +
Any modules that are needed should be imported (not used) in `runtests.jl` not in the sub-test files.  Shortcuts for WaterModels and InfrastructureModels are already defined there.

2021-05-13 21:18 UTC, jjstickel commented
@enzoliuyang94 , I refactored your tests a bit. Please take a look and let me know if all looks Ok.
@tasseff , @claytonpbarrows , you may wish to review this large set of new tests for WNTR simulation and validation.

2021-05-13 21:21 UTC, jjstickel approved these changes

2021-05-13 21:24 UTC, enzoliuyang94 commented
> @enzoliuyang94 , I refactored your tests a bit. Please take a look and let me know if all looks Ok.
> @tasseff , @claytonpbarrows , you may wish to review this large set of new tests for WNTR simulation and validation.

Hi Jonathan, these codes look good to me. Thanks!

2021-05-19 16:58 UTC, merged